/**
 * @file CompanyServiceTests.cpp
 * @brief Tests for CompanyService, CompanyRepository mock, and CompanyServiceImpl conversions
 */
#include "company/company_service.h"
#include "company_repository_mock.h"
#include "gtest/gtest.h"

#include <memory>

using std::unique_ptr;

// ============================================================================
// MockCompanyRepository tests
// ============================================================================

TEST(MockCompanyRepositoryTest, AddAndRetrieve)
{
    MockCompanyRepository repo;
    CompanyData data;
    data.name = "TestCorp";
    data.server_uid = 1;

    CompanyData result = repo.add(data);
    EXPECT_EQ(result.name, "TestCorp");
    EXPECT_FALSE(result.uid.empty());  // uid generated by mock

    auto opt = repo.findByUid(result.uid);
    ASSERT_TRUE(opt.has_value());
    EXPECT_EQ(opt->name, "TestCorp");
    EXPECT_EQ(repo.addCount(), 1);
}

TEST(MockCompanyRepositoryTest, RemoveExisting_ReturnsSuccess)
{
    MockCompanyRepository repo;
    CompanyData data;
    data.name = "ToDelete";
    data = repo.add(data);

    DeleteResult del = repo.remove(data.uid);
    EXPECT_TRUE(del.success);
    EXPECT_EQ(del.uid, data.uid);

    auto opt = repo.findByUid(data.uid);
    EXPECT_FALSE(opt.has_value());
    EXPECT_EQ(repo.removeCount(), 1);
}

TEST(MockCompanyRepositoryTest, RemoveNonExisting_ReturnsFailure)
{
    MockCompanyRepository repo;
    DeleteResult del = repo.remove("nonexistent");
    EXPECT_FALSE(del.success);
    EXPECT_FALSE(del.error.empty());
}

TEST(MockCompanyRepositoryTest, QueryWithFilter_ReturnsMatching)
{
    MockCompanyRepository repo;
    repo.addPreExisting([]() {
        CompanyData d; d.name = "Alpha"; return d;
    }());
    repo.addPreExisting([]() {
        CompanyData d; d.name = "Beta"; return d;
    }());

    CompanyFilter filter;
    filter.value = "Alph";
    auto results = repo.query(filter);
    ASSERT_EQ(results.size(), 1);
    EXPECT_EQ(results[0].name, "Alpha");
}

TEST(MockCompanyRepositoryTest, CountWithFilter_ReturnsCorrectCount)
{
    MockCompanyRepository repo;
    for (int i = 0; i < 5; ++i) {
        CompanyData d;
        d.name = "Test" + std::to_string(i);
        repo.addPreExisting(d);
    }

    CompanyFilter filter;
    EXPECT_EQ(repo.count(filter), 5);

    filter.value = "Test1";
    EXPECT_EQ(repo.count(filter), 1);
}

// ============================================================================
// CompanyService tests (with mock repository)
// ============================================================================

class CompanyServiceTest : public ::testing::Test {
protected:
    void SetUp() override
    {
        auto mock = std::make_unique<MockCompanyRepository>();
        m_mock = mock.get();
        m_service = std::make_unique<CompanyService>(std::move(mock));
    }

    MockCompanyRepository* m_mock = nullptr;
    unique_ptr<CompanyService> m_service;
};

TEST_F(CompanyServiceTest, AddCompany_DelegatesToRepository)
{
    CompanyData data;
    data.name = "NewCo";

    CompanyData result = m_service->addCompany(data);
    EXPECT_EQ(result.name, "NewCo");
    EXPECT_EQ(m_mock->addCount(), 1);
}

TEST_F(CompanyServiceTest, EditCompany_DelegatesToRepository)
{
    CompanyData data;
    data.uid = "existing-uid";
    data.name = "UpdatedCo";

    CompanyData result = m_service->editCompany(data);
    EXPECT_EQ(result.name, "UpdatedCo");
    EXPECT_EQ(m_mock->updateCount(), 1);
}

TEST_F(CompanyServiceTest, DeleteCompany_DelegatesToRepository)
{
    // Pre-add so it exists
    CompanyData d;
    d.name = "DelMe";
    d = m_mock->add(d);

    DeleteResult result = m_service->deleteCompany(d.uid);
    EXPECT_TRUE(result.success);
    EXPECT_EQ(m_mock->removeCount(), 1);
}

TEST_F(CompanyServiceTest, QueryCompanies_DelegatesToRepository)
{
    m_mock->addPreExisting([]() {
        CompanyData d; d.name = "QueryTest"; return d;
    }());

    CompanyFilter filter;
    filter.value = "Query";
    auto results = m_service->queryCompanies(filter);
    ASSERT_EQ(results.size(), 1);
    EXPECT_EQ(results[0].name, "QueryTest");
}

TEST_F(CompanyServiceTest, GetCompanyByUid_Found_ReturnsData)
{
    CompanyData d;
    d.name = "FindMe";
    d = m_mock->add(d);

    auto opt = m_service->getCompanyByUid(d.uid);
    ASSERT_TRUE(opt.has_value());
    EXPECT_EQ(opt->name, "FindMe");
}

TEST_F(CompanyServiceTest, GetCompanyByUid_NotFound_ReturnsNullopt)
{
    auto opt = m_service->getCompanyByUid("does-not-exist");
    EXPECT_FALSE(opt.has_value());
}

TEST_F(CompanyServiceTest, CountCompanies_DelegatesToRepository)
{
    for (int i = 0; i < 3; ++i) {
        CompanyData d;
        d.name = "CountMe";
        m_mock->addPreExisting(d);
    }

    CompanyFilter filter;
    filter.value = "CountMe";
    EXPECT_EQ(m_service->countCompanies(filter), 3);
}

// ============================================================================
// Note: CompanyServiceImpl::toCompanyData and toCompanyFilter are private
// static methods. They are tested indirectly through the service tests above.
// To test them directly, make them public or add friend test declarations.
// ============================================================================
